version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    environment:
      - PUID=1000
      - PGID=1000
      - AUTOMATED_CONVERSION_PRESET=njkwilson/Fast1080QSV
    network_mode: bridge
    devices: 
      - /dev/dri
    ports:
      - "3003:5800"
    volumes:
      - "./config:/config:rw"
      - "./storage:/storage:ro"
      - "./input:/watch:rw"
      - "./output:/output:rw"