version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
        - ./db:/data/db
        - ./configdb:/data/configdb
    network_mode:
      bridge
    ports:
      - 27017:27017
    restart: unless-stopped