# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    network_mode: bridge
    ports:
      - 3036:3036
    restart: always