---
version: "2.1"
services:
  filezilla:
    image: ghcr.io/linuxserver/filezilla
    container_name: filezilla
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    network_mode: bridge
    ports:
      - 1004:3000
    restart: unless-stopped